In [1]:
!which python

/run/media/ashiktonmoy/New Volume/Projects/Code_Snippets/venv/bin/python

In [6]:
import pandas as pd
import os

In [15]:
df = pd.read_csv('Data/hard_features.csv')

In [9]:
destination = os.path.join('Data')
print(destination)
try:
    os.makedirs(destination, exist_ok=True)
#     print("Directory doesn't exist. \nCreating Directory..." )
except OSError as error:
    print(error)

Data
Directory doesn't exist.
Creating Directory...

In [16]:
df.head()

,rear_fname,side_Length_wither,side_Length_shoulderbone,side_F_Girth,side_R_Girth,side_height,rear_width,rear_height,actual_width,bg,cattle,sticker
0,100_r_109_M.jpg,2064,2195,1040,1009,1987,723,2332,616.038165,9622541,3308833,47826
1,100_r_131_F.jpg,2042,2183,1027,1027,2121,795,2191,769.600639,9372257,3554744,52199
2,100_r_181_F.jpg,2091,2135,978,978,2209,816,2357,764.761986,9523218,3403174,52808
3,101_r_128_F.jpg,2109,2162,1002,970,1941,827,2123,756.103156,9943689,2992012,43499
4,101_r_131_F.jpg,2056,2026,990,924,2112,519,1574,696.396442,9648556,3285803,44841

In [ ]:
# for item in df:
#     item

In [17]:
df.rear_fname.str.split(pat='_',expand=True)

        0  1    2      3
0     100  r  109  M.jpg
1     100  r  131  F.jpg
2     100  r  181  F.jpg
3     101  r  128  F.jpg
4     101  r  131  F.jpg
...   ... ..  ...    ...
2461  309  r  177  F.jpg
2462  309  r  192  F.jpg
2463  309  r  194  F.jpg
2464  309  r  262  F.jpg
2465   30  r  110  F.jpg

[2466 rows x 4 columns]

In [18]:
df.rear_fname.str.split(pat='_',expand=True)[2]

0       109
1       131
2       181
3       128
4       131
       ...
2461    177
2462    192
2463    194
2464    262
2465    110
Name: 2, Length: 2466, dtype: object

In [22]:
df['weight']=df.rear_fname.str.split(pat='_',expand=True)[2]
# print(df)

In [24]:
df.head()

,rear_fname,side_Length_wither,side_Length_shoulderbone,side_F_Girth,side_R_Girth,side_height,rear_width,rear_height,actual_width,bg,cattle,sticker,weight
0,100_r_109_M.jpg,2064,2195,1040,1009,1987,723,2332,616.038165,9622541,3308833,47826,109
1,100_r_131_F.jpg,2042,2183,1027,1027,2121,795,2191,769.600639,9372257,3554744,52199,131
2,100_r_181_F.jpg,2091,2135,978,978,2209,816,2357,764.761986,9523218,3403174,52808,181
3,101_r_128_F.jpg,2109,2162,1002,970,1941,827,2123,756.103156,9943689,2992012,43499,128
4,101_r_131_F.jpg,2056,2026,990,924,2112,519,1574,696.396442,9648556,3285803,44841,131

In [26]:
savefile_name='hard_features_With_weight_v1.csv'
df.to_csv(os.path.join(destination,savefile_name))